/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './angular-billboard.component';
const styles_AngularBillboardComponent:any[] = ([] as any[]);
export const RenderType_AngularBillboardComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_AngularBillboardComponent,data:{}});
export function View_AngularBillboardComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_AngularBillboardComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'angular-billboard',
      ([] as any[]),(null as any),(null as any),(null as any),View_AngularBillboardComponent_0,
      RenderType_AngularBillboardComponent)),i0.ɵdid(114688,(null as any),0,i1.AngularBillboardComponent,
      [i0.Renderer2,i0.ElementRef],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AngularBillboardComponentNgFactory:i0.ComponentFactory<i1.AngularBillboardComponent> = i0.ɵccf('angular-billboard',
    i1.AngularBillboardComponent,View_AngularBillboardComponent_Host_0,{chart:'chart'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvamVjdC9hbmd1bGFyLWJpbGxib2FyZC9zcmMvYW5ndWxhci1iaWxsYm9hcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3Byb2plY3QvYW5ndWxhci1iaWxsYm9hcmQvc3JjL2FuZ3VsYXItYmlsbGJvYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L3Byb2plY3QvYW5ndWxhci1iaWxsYm9hcmQvc3JjL2FuZ3VsYXItYmlsbGJvYXJkLmNvbXBvbmVudC50cy5Bbmd1bGFyQmlsbGJvYXJkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFuZ3VsYXItYmlsbGJvYXJkPjwvYW5ndWxhci1iaWxsYm9hcmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTswQ0FBQSxVQUFBO01BQUE7SUFBQTs7Ozs7In0=
