/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './angular-billboard.module';
import * as i2 from './angular-billboard.service';
export const AngularBillboardModuleNgFactory:i0.NgModuleFactory<i1.AngularBillboardModule> = i0.ɵcmf(i1.AngularBillboardModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.AngularBillboardService,i2.AngularBillboardService,([] as any[])),i0.ɵmpd(512,
          i1.AngularBillboardModule,i1.AngularBillboardModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvamVjdC9hbmd1bGFyLWJpbGxib2FyZC9zcmMvYW5ndWxhci1iaWxsYm9hcmQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3Byb2plY3QvYW5ndWxhci1iaWxsYm9hcmQvc3JjL2FuZ3VsYXItYmlsbGJvYXJkLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
